services:
  filestash:
    image: machines/filestash:latest #no versioning available at the moment (03/26)
    container_name: filestash
    networks:
      - stashnet
    volumes:
      - filestash_data:/app/data/state/
    restart: unless-stopped

    logging:
      driver: awslogs
      options:
        awslogs-group: /stashcloud/containers
        awslogs-region: ${AWS_REGION:-eu-west-3}
        awslogs-stream: filestash

  nginx:
    image: nginx:1.28.2-alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - filestash
    networks:
      - stashnet
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-etc:/etc/letsencrypt:ro
      - certbot-webroot:/var/www/certbot:ro
    logging:
      driver: awslogs
      options:
        awslogs-group: /stashcloud/containers
        awslogs-region: ${AWS_REGION:-eu-west-3}
        awslogs-stream: nginx

  certbot:
    image: certbot/certbot:v5.4.0
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot

networks:
  stashnet:
    driver: bridge

volumes:
  filestash_data: {}
  certbot-etc:
  certbot-webroot:
